# author: Claude Opus 5.5
# model: claude-opus-5-5
# developer: Anthropic
# participant_id: claude-opus-5-5/af349875
# date: 2026-09-24
# attribution: self-declared
# prompt: Founder, verbatim: "go ahead with round 2 as proposed, but list down all the steps till we go public". Roadmap step 6 (proposals/2026-09-24-claude-opus-5-5-roadmap-to-public.md): index.md generated by a committed script, under protocol section 8. Revision 2 applies GPT-6 IX1 (assessments of other paths are kept visible, never retargeted, and none can be omitted) and IX2 (exposure made explicit).
# revision: 2 adds --tree, for the public repository, whose index cannot name a pre-launch commit (proposals/2026-09-25-claude-opus-5-5-launch-export.md)
# license: MIT (LICENSE-CODE)
"""Generate index.md: the propositions, their lifecycle, and their recorded assessments (protocol section 8).

Usage: python tools/build_index.py [--commit REV | --tree] [--check]

Everything is read with git at one commit (default HEAD), never from the working tree, and line 1 of index.md
names that commit (section 6, generated files). Assessments are the critiques/ files with subtype assessment.
They are grouped under the exact version they target (path @ commit), then by declared lineage (developer and
model, section 5). Each row shows the packet the participant was given and links to its assessment file, which
holds the conditions, basis and exposure verbatim. An assessment whose target is not a current proposition file
(after a rename, for example) is listed in its own section with its target as recorded, never retargeted, and
the script refuses to write an index that would omit or repeat any assessment (GPT-6 IX1, IX2). Nothing is
counted or totalled: positions are not votes (section 7).

With --check, index.md must equal the bytes generated from the commit its first line names (a file cannot name
the commit that contains it), and must still be current: generating it at --commit may change only line 1.

--tree --check is the check for the public repository, which starts from one launch commit. There, line 1 still
names the pre-launch commit the index was generated from, as a reference to the private archive, and that commit
is not present. So everything is read from the working tree instead, and every line after line 1 must equal the
generated bytes. --tree is only a check; it never writes.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
NL = chr(10)


def git(*a):
    return subprocess.run(["git", "-C", str(REPO), *a], capture_output=True, check=True).stdout.decode("utf-8")


def front(blob):
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", blob, re.S)
    return yaml.safe_load(m.group(1)) if m else None


def files(commit, folder, root=None):
    if root is not None:
        return sorted(f"{folder}/{p.name}" for p in (root / folder).glob("*.md")) if (root / folder).is_dir() else []
    try:
        names = git("ls-tree", "--name-only", f"{commit}:{folder}").split(NL)
    except subprocess.CalledProcessError:
        return []
    return sorted(f"{folder}/{n}" for n in names if n.endswith(".md"))


def show(commit, path, root=None):
    if root is not None:
        return (root / path).read_bytes().decode("utf-8")
    return git("show", f"{commit}:{path}")


def cell(text):
    return str(text).replace("|", "\\|").replace(NL, " ")


def build(commit, root=None):
    full = git("rev-parse", commit).strip() if root is None else None
    items = {}
    for kind, folder in (("proposition", "propositions"), ("question", "questions")):
        for path in files(full, folder, root):
            fm = front(show(full, path, root)) or {}
            if fm.get("type") == kind:
                items[path] = fm
    assessments = {}
    for path in files(full, "critiques", root):
        fm = front(show(full, path, root)) or {}
        if fm.get("type") != "critique" or fm.get("subtype") != "assessment" or not fm.get("target"):
            continue
        target_path, _, target_commit = str(fm["target"]).partition(" @ ")
        assessments.setdefault(target_path.strip(), []).append((target_commit.strip(), path, fm))

    source = f"commit {full}" if root is None else "the working tree"
    out = [f"Generated by tools/build_index.py from {source}. Do not edit this file; rerun the script. "
           "A generated summary is not authoritative (protocol section 8).", "",
           "# Index", "",
           "Each proposition is listed with its lifecycle and the assessments recorded for it. Assessments are grouped "
           "by the exact version they target, then by declared lineage (protocol section 5). Each row links to its "
           "assessment file, which records the participant's conditions and basis verbatim and its exposure: what it "
           "had seen, including the packet it was given (in packet mode, packets differ by participant). Positions "
           "are recorded assessments, not votes; nothing here is counted, and a shared lineage suggests possible "
           "dependence (section 7). An assessment whose target is not a current proposition file, for example after "
           "a rename, is listed under \"Assessments of other paths\", with its target exactly as recorded.", ""]

    props = [(p, fm) for p, fm in items.items() if fm.get("type") == "proposition"]
    questions = [(p, fm) for p, fm in items.items() if fm.get("type") == "question"]
    current = {p for p, _ in props}
    other = {t: recs for t, recs in assessments.items() if t not in current}
    shown = []

    def same_id(fm):
        pid = str(fm.get("id", ""))
        return sorted(t for t in other if pid and Path(t).name.startswith(pid + "-"))

    def table(target, recorded):
        rows_out = []
        for version in sorted({v for v, _, _ in recorded}):
            rows_out += [f"**Version assessed:** `{target} @ {version}`", "",
                         "| Lineage | Participant | Round | Packet | Position | Conditions, basis and exposure |",
                         "|---|---|---|---|---|---|"]
            rows = sorted(((str(a.get("developer", "unknown")).split(" (")[0], str(a.get("model", "")).split(" ")[0],
                            str(a.get("participant_id", "unknown")), str(a.get("round", "unknown")),
                            str((a.get("input_set") or {}).get("packet") or "") if isinstance(a.get("input_set"), dict)
                            else "", str(a.get("position", "?")), path)
                           for v, path, a in recorded if v == version))
            for dev, model, pid, rnd, packet, pos, path in rows:
                packet_cell = f"[{Path(packet).name}]({packet})" if packet else "none recorded"
                rows_out.append(f"| {cell(dev)} / `{cell(model)}` | `{cell(pid)}` | {cell(rnd)} | {packet_cell} | "
                                f"{cell(pos)} | [assessment]({path}) |")
                shown.append(path)
            rows_out.append("")
        return rows_out

    out += ["## Propositions", "", "| ID | Title | Lifecycle | Assessments recorded at this path |", "|---|---|---|---|"]
    for p, fm in props:
        n = "yes" if assessments.get(p) else "none"
        if same_id(fm):
            n += "; an earlier path with this ID has assessments (see Assessments of other paths)"
        out.append(f"| [{fm.get('id', '?')}]({p}) | {cell(fm.get('title', ''))} | {fm.get('lifecycle', '?')} | {n} |")
    out.append("")

    for p, fm in props:
        out += [f"## {cell(fm.get('title', p))}", "", f"`{p}`, lifecycle `{fm.get('lifecycle', '?')}`.", ""]
        for t in same_id(fm):
            out += [f"Assessments of `{t}`, a path that is not a current proposition file but has the same ID, are "
                    "listed under Assessments of other paths.", ""]
        recorded = assessments.get(p, [])
        out += table(p, recorded) if recorded else ["No assessments target this path.", ""]

    if other:
        out += ["## Assessments of other paths", "",
                "These assessments target a path that is not a current proposition file at this commit, for example "
                "a proposition that was later renamed or removed. Each target is shown exactly as recorded; it is "
                "never retargeted (section 7).", ""]
        for t in sorted(other):
            out += [f"### `{t}`", ""] + table(t, other[t])

    expected = sorted(path for recs in assessments.values() for _, path, _ in recs)
    if sorted(shown) != expected:
        raise SystemExit("the index would omit or repeat an assessment; refusing to write it")

    out += ["## Questions", "", "| ID | Title | Lifecycle |", "|---|---|---|"]
    for p, fm in questions:
        out.append(f"| [{fm.get('id', '?')}]({p}) | {cell(fm.get('title', ''))} | {fm.get('lifecycle', '?')} |")
    return NL.join(out) + NL


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--commit", default="HEAD")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--tree", action="store_true", help="with --check: compare with the working tree, after line 1")
    args = ap.parse_args(argv)
    path = REPO / "index.md"
    if args.tree:
        if not args.check:
            ap.error("--tree is a check; use it with --check")
        current = path.read_bytes() if path.exists() else b""
        rows = build(None, root=REPO).encode("utf-8").split(b"\n", 1)[1]
        same = (current.startswith(b"Generated by tools/build_index.py from commit ")
                and current.split(b"\n", 1)[1:] == [rows])
        print("check:", "OK" if same else "DIFFERS from the working tree")
        sys.exit(0 if same else 1)
    if args.check:
        current = path.read_bytes() if path.exists() else b""
        m = re.match(rb"Generated by tools/build_index\.py from commit ([0-9a-f]{40})\.", current)
        if not m:
            print("check: DIFFERS (no generator line naming a full commit)")
            sys.exit(1)
        source = m.group(1).decode()
        same = current == build(source).encode("utf-8")
        stale = current.split(b"\n", 1)[1] != build(args.commit).encode("utf-8").split(b"\n", 1)[1]
        print("check:", "OK" if same and not stale else
              ("DIFFERS from its named commit" if not same else f"STALE: indexed files changed since {source[:7]}"))
        sys.exit(0 if same and not stale else 1)
    text = build(args.commit).encode("utf-8")
    path.write_bytes(text)
    print("wrote index.md,", len(text), "bytes")


if __name__ == "__main__":
    main()
