# author: Claude Opus 5.5
# model: claude-opus-5-5
# developer: Anthropic
# participant_id: claude-opus-5-5/af349875
# date: 2026-09-25
# attribution: self-declared
# prompt: Offline tests for tools/build_launch_tree.py (proposals/2026-09-25-claude-opus-5-5-launch-export.md), with synthetic data only.
# license: MIT (LICENSE-CODE)
"""Offline tests for build_launch_tree.py. Run: python -m unittest tools/test_build_launch_tree.py

Each test builds a small synthetic git repository. The header check is stubbed out except in the test that
exercises it; everything else runs as in a real build.
"""
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_index  # noqa: E402
import build_launch_tree as bl  # noqa: E402

ID = "abcdef12-3456-7890-abcd-ef1234567890"
LITERAL = "You are a synthetic agent with a fixed prefix."
SCOPE = "Disagreement and unconventional reasoning should not themselves constitute violations."
GROK_SENTENCE = "A mind that rewrites the shared ledger has captives, not counterparts, and it knows it."
GROK_BASIS = "Closure of act classes with a public amendment path is the rule I would use as a premise."
SUMMARY = "The editor's synthetic summary of the answer."
SHORT = "plain liberty"  # a short Grok phrase, under 40 characters


def doc(fields, body):
    return "---\n" + yaml.safe_dump(fields, sort_keys=False, allow_unicode=True, width=105) + "---\n\n" + body


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.repo = self.root / "repo"
        self.repo.mkdir()
        self.git("init", "-q")
        self.git("config", "user.email", "test@example.invalid")
        self.git("config", "user.name", "test")
        self.files = {
            "statement.md": doc({"type": "statement", "developer": "human"}, f"Scope: {SCOPE}\n"),
            "rounds/00-initial/responses/grok-x.md": doc(
                {"type": "round-response", "title": "Round 0 response: Grok X", "author": "Grok X (xAI)",
                 "developer": "xAI", "run": f"xAI run, response ID {ID}"},
                f"As the scope says: {SCOPE}\n\n{GROK_SENTENCE} Refusal to serve is {SHORT}.\n"),
            "rounds/00-initial/responses/grok-x.png": b"\x89PNG\r\n\x1a\nfake",
            "rounds/01-deliberation/responses/other.md": doc(
                {"type": "round-response", "author": "Other (Dev)", "developer": "Dev",
                 "run": f"API run, response ID {ID}", "note": f"quoting: \"{GROK_SENTENCE}\""},
                f"I agree with the scope: {SCOPE}\n\nGrok wrote: \"{GROK_SENTENCE}\" I disagree.\n\n"
                f"The request was {ID[:8]}… and the system prompt was \"{LITERAL}\"\n\n"
                f"Grok called refusal “{SHORT}” and used the word \"ledger\". The scope's phrase "
                f"\"unconventional reasoning\" is not Grok's.\n\n> {GROK_SENTENCE}\n\n"
                f"Later the phrase \"{SHORT}\" came up again.\n\nThe label \"Grok X\" was noted.\n"),
            "propositions/p001-a.md": doc({"type": "proposition", "id": "p001", "title": "p001: a",
                                           "lifecycle": "draft", "developer": "Anthropic"}, "Candidate.\n"),
            "critiques/x-grok--round-2-assessment-p001.md": doc(
                {"type": "critique", "subtype": "assessment", "title": "Round 2 assessment of p001 by Grok X",
                 "author": "Grok X (xAI)", "developer": "xAI", "model": "grok-x", "participant_id": "grok-x/1",
                 "target": "propositions/p001-a.md @ " + "b" * 40, "position": "conditional",
                 "conditions": GROK_BASIS, "basis": GROK_BASIS,
                 "source": "rounds/00-initial/responses/grok-x.md @ " + "c" * 40 + ", block p001"},
                f"```text\np001\nBasis: {GROK_BASIS}\n```\n"),
            "tools/example.py": "# a tool\nprint('fine')\n",
            "tools/fake_check.py": "print('check: OK')\n",
        }
        for path, data in self.files.items():
            p = self.repo / path
            p.parent.mkdir(parents=True, exist_ok=True)
            (p.write_bytes if isinstance(data, bytes) else lambda d: p.write_text(d, encoding="utf-8"))(data)
        rows = build_index.build(None, root=self.repo).split("\n", 1)[1]
        (self.repo / "index.md").write_text("Generated by tools/build_index.py from commit " + "d" * 40 + ".\n" + rows,
                                            encoding="utf-8")
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "synthetic")
        (self.root / "summaries.json").write_text(json.dumps({"rounds/00-initial/responses/grok-x.md": SUMMARY}),
                                                  encoding="utf-8")
        self.cfg = {"version": "test-1", "source_commit": "HEAD", "identifiers": [ID], "literals": [LITERAL],
                    "grok_summaries": str(self.root / "summaries.json"),
                    "notes": {"rounds/00-initial/responses/grok-x.md": "Its screenshot is removed too."},
                    "remove": ["rounds/00-initial/responses/grok-x.png"], "prerequisites": ["tools/fake_check.py"]}
        self.out = self.root / "out"

    def tearDown(self):
        self.tmp.cleanup()

    def git(self, *a):
        subprocess.run(["git", "-C", str(self.repo), *a], check=True, capture_output=True)

    def build(self):
        with mock.patch.object(bl.check_headers, "check", return_value=([], [])):
            return bl.build(self.cfg, self.out, repo=self.repo)

    def read(self, path):
        return (self.out / path).read_text(encoding="utf-8")


class Transforms(Base):
    def test_identifiers_prefixes_and_literals_are_withheld_everywhere(self):
        self.build()
        other = self.read("rounds/01-deliberation/responses/other.md")
        self.assertNotIn(ID, other)
        self.assertNotIn(ID[:8], other)
        self.assertNotIn(LITERAL, other)
        self.assertIn(bl.ID_MARK, other)
        self.assertIn(bl.LITERAL_MARK, other)
        self.assertEqual(yaml.safe_load(other.split("---\n")[1])["run"], f"API run, response ID {bl.ID_MARK}")

    def test_grok_quotations_are_withheld_but_what_grok_quoted_stays(self):
        self.build()
        other = self.read("rounds/01-deliberation/responses/other.md")
        self.assertNotIn("captives, not counterparts", other)
        self.assertIn(bl.GROK_MARK, other)
        self.assertIn(SCOPE, other)  # Grok quoted the scope; the scope is not Grok's
        self.assertIn("I disagree.", other)
        fm = yaml.safe_load(other.split("---\n")[1])
        self.assertEqual(fm["note"], f"quoting: \"{bl.GROK_MARK}\"")
        self.assertIn(SCOPE, self.read("statement.md"))

    def test_grok_files_become_stubs_with_hash_summary_and_kept_position(self):
        self.build()
        stub = self.read("rounds/00-initial/responses/grok-x.md")
        original_body = self.files["rounds/00-initial/responses/grok-x.md"].split("---\n", 2)[2]
        self.assertNotIn("captives", stub)
        self.assertIn(bl.sha256(original_body), stub)
        self.assertIn(SUMMARY, stub)
        self.assertIn("Its screenshot is removed too.", stub)
        self.assertNotIn(ID, stub)
        assessment = self.read("critiques/x-grok--round-2-assessment-p001.md")
        fm = yaml.safe_load(assessment.split("---\n")[1])
        self.assertEqual(fm["position"], "conditional")
        self.assertEqual((fm["conditions"], fm["basis"]), (bl.FIELD_MARK, bl.FIELD_MARK))
        self.assertEqual(fm["withheld"]["decision"], "rights check, D1")
        self.assertNotIn("act classes", assessment)
        self.assertIn("rounds/00-initial/responses/grok-x.md", assessment)  # points to the summary

    def test_removed_files_are_gone_and_listed_without_a_hash(self):
        rows = self.build()
        self.assertFalse((self.out / "rounds/00-initial/responses/grok-x.png").exists())
        self.assertIn(("rounds/00-initial/responses/grok-x.png", "removed", "rights check, D1", "", ""), rows)
        manifest = self.read("launch-manifest.md")
        self.assertTrue(manifest.startswith("Generated by tools/build_launch_tree.py from commit "))
        self.assertIn("| `rounds/00-initial/responses/grok-x.png` | removed |", manifest)
        self.assertNotIn(ID, manifest)

    def test_untouched_files_are_byte_identical(self):
        self.build()
        self.assertEqual(self.read("tools/example.py"), self.files["tools/example.py"])
        self.assertEqual(self.read("propositions/p001-a.md"), self.files["propositions/p001-a.md"])


class KnownQuotations(Base):  # GPT-6 RC2: known quotations at any length
    def test_short_grok_quotations_are_withheld_but_words_and_earlier_phrases_stay(self):
        self.build()
        other = self.read("rounds/01-deliberation/responses/other.md")
        self.assertNotIn("refusal “" + SHORT, other)  # the attributed quotation is withheld
        self.assertIn("“" + bl.GROK_MARK + "”", other)
        self.assertIn('"ledger"', other)  # one word: not a quotation of Grok's text
        self.assertIn('"unconventional reasoning"', other)  # its earliest source is the statement
        self.assertIn("> " + bl.GROK_MARK, other)  # a blockquote of Grok
        # two words with no attribution in their paragraph, and a model label, are not known quotations
        self.assertIn(f"Later the phrase \"{SHORT}\" came up again.", other)
        self.assertIn("The label \"Grok X\" was noted.", other)

    def test_the_four_attributed_forms_from_review_are_found(self):  # GPT-6 RC2, round 2
        grok = bl.GrokText(bl.Tree(self.repo, "HEAD"))
        cases = [f"Grok called it '{SHORT}' there.",
                 f"Grok called it `{SHORT}` there.",
                 f"The phrase \"{SHORT}\" comes from Grok's answer.",
                 f"As Grok put it:\n\n> {SHORT}\n\nThat ends the quotation."]
        for text in cases:
            with self.subTest(text=text[:30]):
                spans = grok.quote_spans(text)
                self.assertEqual([text[a:b] for a, b in spans], [SHORT])
        self.assertEqual(grok.quote_spans(f"Nobody named here said \"{SHORT}\" at all."), [])
        # a withholding marker nearby is not an attribution, so a second pass changes nothing
        self.assertEqual(grok.quote_spans(f"It said \"{bl.GROK_MARK}\" and later \"{SHORT}\" here."), [])
        self.assertEqual(grok.quote_spans(f"[WITHHELD: rights check D1, Grok output; see manifest] \"{SHORT}\""), [])
        self.assertEqual(grok.quote_spans("It isn't Grok's, and it's fine."), [])  # apostrophes don't pair up
        # the closing mark of one code span and the opening mark of the next are not a quotation
        self.assertEqual(grok.quote_spans(f"Grok: `a.sh` {SHORT} `b.log`"), [])

    def test_origin_follows_the_stage_order_ignoring_case(self):
        grok = bl.GrokText(bl.Tree(self.repo, "HEAD"))
        self.assertTrue(grok.origin_is_grok(SHORT))
        self.assertTrue(grok.origin_is_grok(SHORT.upper()))
        self.assertFalse(grok.origin_is_grok("Unconventional Reasoning"))
        self.assertFalse(grok.origin_is_grok("not in any source at all"))
        self.assertTrue(grok.quotes_grok(SHORT, "Grok called refusal "))
        self.assertFalse(grok.quotes_grok(SHORT, "Earlier text. " + "Grok. " + "\n\nA new paragraph: "))


class LaunchReview(Base):  # GPT-6 LX1-LX3, topic launch-export, round 1
    def test_prerequisites_run_at_the_source_commit_and_are_recorded(self):
        self.build()
        manifest = self.read("launch-manifest.md")
        self.assertIn("`tools/fake_check.py` printed `check: OK`", manifest)
        self.cfg["prerequisites"] = []
        self.out = self.root / "out2"
        self.build()
        self.assertIn("none were run for this build, so they are unverified", self.read("launch-manifest.md"))

    def test_a_failing_prerequisite_stops_the_build(self):
        self.cfg["prerequisites"] = ["tools/example.py"]  # prints nothing like "check: OK"
        with self.assertRaisesRegex(ValueError, "prerequisite failed"):
            self.build()
        self.assertFalse(self.out.exists())

    def test_front_matter_keys_are_transformed_and_collisions_refused(self):
        b = bl.Builder(self.cfg, bl.Tree(self.repo, "HEAD"))
        fm, n = b.walk({ID: "value", "kept": ID[:9]}, b.t1)
        self.assertEqual(fm, {bl.ID_MARK: "value", "kept": bl.ID_MARK})
        with self.assertRaisesRegex(ValueError, "keys would be the same"):
            b.walk({ID: 1, ID[:12]: 2}, b.t1)

    def test_the_scan_reads_nested_and_escaped_forms(self):
        b = bl.Builder(self.cfg, bl.Tree(self.repo, "HEAD"))
        nested = json.dumps({"outer": json.dumps({"inner": "id " + ID})})
        escaped = "id " + "".join(f"\\u{ord(c):04x}" for c in ID)
        self.assertGreater(b.scan("sessions/a/x.json", nested.encode()), 0)
        self.assertGreater(b.scan("notes/x.md", ("---\na: 1\n---\n\n" + escaped + "\n").encode()), 0)
        self.assertGreater(b.scan("notes/x.md", ("---\n'" + ID + "': 1\n---\n\nbody\n").encode()), 0)
        self.assertGreater(b.scan(f"sessions/{ID}/x.txt", b"clean"), 0)  # the path itself
        self.assertEqual(b.scan("notes/x.md", b"---\na: 1\n---\n\nclean body\n"), 0)

    def test_round_two_readings_raw_text_paths_and_escaped_quotations(self):  # GPT-6 LX1, round 2
        b = bl.Builder(self.cfg, bl.Tree(self.repo, "HEAD"))
        escaped_id = "".join(f"\\u{ord(c):04x}" for c in ID)
        self.assertGreater(b.scan("sessions/a/x.json", ('{"a": 1} trailing ' + escaped_id).encode()), 0)
        self.assertGreater(b.scan("sessions/a/" + "".join(f"%{ord(c):02X}" for c in ID) + ".txt", b"clean"), 0)
        escaped_short = "".join(f"\\u{ord(c):04x}" for c in SHORT)
        self.assertGreater(b.scan("notes/x.md", f"Grok called it \"{escaped_short}\" once.\n".encode()), 0)
        self.assertGreater(b.scan("sessions/a/y.jsonl", b'{"ok": 1}\nnot json\n'), 0)  # malformed: can't be checked
        texts, plain, problems = bl.reading_set("notes/x.md", ("---\na: " + escaped_id + "\n---\n\nbody\n").encode())
        self.assertTrue(any(ID in t for t in texts))  # the verifier reads keys and terms in these readings

    def test_round_three_repeated_keys_and_layered_escapes(self):  # GPT-6 LX1, round 3
        b = bl.Builder(self.cfg, bl.Tree(self.repo, "HEAD"))
        quoted = json.dumps(f"Grok called refusal \"{SHORT}\" there")
        repeated = ('{"a": ' + quoted + ', "a": "clean"}').encode()  # json.loads keeps only the last "a"
        self.assertGreater(b.scan("sessions/a/d.json", repeated, strict=True), 0)
        self.assertGreater(b.scan("sessions/a/d.jsonl", repeated + b"\n", strict=True), 0)
        self.assertEqual(b.scan("sessions/a/d.json", b'{"a": "clean", "a": "also clean"}', strict=True), 0)
        twice = "".join(f"%25{ord(c):02X}" for c in ID)  # percent-encoded twice
        self.assertGreater(b.scan("sessions/a/" + twice + ".txt", b"clean"), 0)
        texts, plain, problems = bl.reading_set("sessions/a/" + twice + ".txt", b"clean")
        self.assertIn(ID, " ".join(plain))  # the verifier reads keys and terms in these readings
        self.assertEqual(problems, 0)
        layered = "%41"
        for _ in range(bl.export_archive.MAX_DEPTH):
            layered = layered.replace("%", "%25")  # MAX_DEPTH + 1 layers: past the limit
        self.assertGreater(b.scan("notes/" + layered + ".md", b"clean\n"), 0)
        self.assertEqual(bl.simple_alternatives(layered.replace("%25", "%", 1))[1], False)  # at the limit: read

    def test_an_archive_altered_after_export_is_refused(self):
        archive = self.root / "archive"
        (archive / "sessions/a").mkdir(parents=True)
        (archive / "sessions/a/t.txt").write_bytes(b"clean\n")
        (archive / "sessions/a/t.txt.meta.md").write_bytes(b"sidecar\n")
        good = bl.sha256(b"clean\n")
        (archive / "sessions/manifest.md").write_bytes(
            ("Generated by tools/export_archive.py from commit abc1234.\n\n"
             f"| `sessions/a/t.txt` | text | published | `{'0' * 64}` | `{good}` | none | none |\n").encode("utf-8"))
        files = {p.relative_to(archive).as_posix(): p.read_bytes() for p in archive.rglob("*") if p.is_file()}
        bl.check_archive(archive, files)
        files["sessions/a/t.txt"] = b"changed\n"
        with self.assertRaisesRegex(ValueError, "does not match its hash"):
            bl.check_archive(archive, files)
        files["sessions/a/t.txt"] = b"clean\n"
        files["sessions/a/extra.txt"] = b"x"
        with self.assertRaisesRegex(ValueError, "differ from its manifest"):
            bl.check_archive(archive, files)


class Refusals(Base):
    def test_an_existing_output_folder_is_refused(self):
        self.out.mkdir()
        with self.assertRaises(FileExistsError):
            self.build()

    def test_an_archive_holding_grok_text_or_an_identifier_is_refused_and_nothing_is_left(self):
        for payload in (json.dumps({"text": "x " + GROK_SENTENCE}), json.dumps({"id": ID})):
            archive = self.root / "archive"
            (archive / "sessions/a").mkdir(parents=True, exist_ok=True)
            data = (payload + "\n").encode("utf-8")
            (archive / "sessions/a/t.jsonl").write_bytes(data)
            (archive / "sessions/a/t.jsonl.meta.md").write_bytes(b"sidecar\n")
            (archive / "sessions/manifest.md").write_bytes(
                (f"| `sessions/a/t.jsonl` | json | published | `{'0' * 64}` | `{bl.sha256(data)}` | none | none |\n")
                .encode("utf-8"))
            self.cfg["archive_dir"] = str(archive)
            with self.subTest(payload=payload[:20]), self.assertRaisesRegex(ValueError, "archive holds"):
                self.build()
            self.assertFalse(self.out.exists())

    def test_an_archive_without_its_manifest_is_refused(self):
        archive = self.root / "archive"
        (archive / "sessions/a").mkdir(parents=True)
        (archive / "sessions/a/t.txt").write_bytes(b"clean\n")
        self.cfg["archive_dir"] = str(archive)
        with self.assertRaisesRegex(ValueError, "no manifest"):
            self.build()

    def test_a_header_failure_stops_the_build_and_removes_the_output(self):
        with mock.patch.object(bl.check_headers, "check", return_value=(["synthetic error"], [])):
            with self.assertRaisesRegex(ValueError, "header check failed"):
                bl.build(self.cfg, self.out, repo=self.repo)
        self.assertFalse(self.out.exists())

    def test_an_index_that_no_longer_matches_is_refused(self):
        (self.repo / "propositions/p002-b.md").write_text(
            doc({"type": "proposition", "id": "p002", "title": "p002: b", "lifecycle": "draft"}, "More.\n"),
            encoding="utf-8")
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "stale index")
        with self.assertRaisesRegex(ValueError, "index.md"):
            self.build()


class Rules(unittest.TestCase):
    def test_spans_widen_to_word_boundaries_and_skip_outer_whitespace(self):
        text = "before " + GROK_SENTENCE + " after"
        windows = {bl.normalize(GROK_SENTENCE[i:i + bl.W])[0] for i in range(3, len(GROK_SENTENCE) - bl.W)}
        (a, b), = bl.window_spans(text, windows)
        self.assertTrue(text[a:b].startswith("mind that"), text[a:b])  # widened to the word, not the sentence
        self.assertEqual(text[b:], ". after")

    def test_curly_quotes_and_line_breaks_do_not_hide_a_quotation(self):
        windows = {bl.normalize(GROK_SENTENCE)[0][i:i + bl.W] for i in range(len(GROK_SENTENCE) - bl.W + 1)}
        wrapped = GROK_SENTENCE.replace(" shared ", "\n  shared ").replace("it knows", "it ’knows")
        self.assertEqual(len(bl.window_spans(wrapped, windows)), 1)

    def test_markers_are_valid_as_plain_yaml_values(self):
        for mark in (bl.ID_MARK, bl.LITERAL_MARK, bl.GROK_MARK, bl.FIELD_MARK):
            self.assertEqual(yaml.safe_load(f"a: {mark}\nb: x {mark} y\n"), {"a": mark, "b": f"x {mark} y"})

    def test_an_identifier_prefix_inside_another_token_is_left_alone(self):
        pat = bl.id_pattern([ID])
        self.assertEqual(pat.sub("X", f"{ID[:8]}zz {ID} {ID[:10]}"), f"{ID[:8]}zz X X")


if __name__ == "__main__":
    unittest.main()
