# author: Claude Opus 5.5
# model: claude-opus-5-5
# developer: Anthropic
# participant_id: claude-opus-5-5/af349875
# date: 2026-09-25
# attribution: self-declared
# prompt: Offline tests for tools/verify_launch.py, which had no suite of its own (GPT-6 LX1 and LX2, topic launch-export, round 1). Synthetic data only.
# license: MIT (LICENSE-CODE)
"""Offline tests for verify_launch.py. Run: python -m unittest tools/test_verify_launch.py

The git, header, unit-test and index subprocesses are stubbed; each test builds a small synthetic checkout.
"""
import hashlib
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_launch_tree as bl  # noqa: E402
import verify_launch as vl  # noqa: E402


def h(data):
    return hashlib.sha256(data).hexdigest()


def ok_run(cmd, cwd):
    if cmd[:2] == ["git", "rev-list"]:
        return subprocess.CompletedProcess(cmd, 0, "c" * 40 + "\n", "")
    if cmd[:2] == ["git", "for-each-ref"]:
        return subprocess.CompletedProcess(cmd, 0, "refs/heads/main\n", "")
    return subprocess.CompletedProcess(cmd, 0, "check: OK\nOK\n", "")


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.clone = Path(self.tmp.name) / "clone"
        self.clone.mkdir()
        self.files = {"a.md": b"# A\n\nSee [b](b.md).\n", "b.md": b"# B\n"}
        self.extra_rows = []

    def tearDown(self):
        self.tmp.cleanup()

    def write(self, checks=True, blank=None, rows=None):
        for p, data in self.files.items():
            (self.clone / p).parent.mkdir(parents=True, exist_ok=True)
            (self.clone / p).write_bytes(data)
        lines = ["Generated by tools/build_launch_tree.py from commit " + "d" * 40 + ".", "",
                 "- **Checks that need the private archive,** run by this build: " +
                 ("; ".join(f"`{c}` printed `check: OK`" for c in bl.PREREQUISITES) if checks else "none"), "",
                 "| Path | Disposition | Changes | At the source commit | At launch |", "|---|---|---|---|---|"]
        for p, data in sorted(self.files.items()):
            digest = "" if p == blank else f"`{h(data)}`"
            lines.append(f"| `{p}` | unchanged |  | `{h(data)}` | {digest} |")
        lines += self.extra_rows + (rows or []) + ["| `launch-manifest.md` | generated | this file |  |  |"]
        (self.clone / "launch-manifest.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    def results(self):
        with mock.patch.object(vl, "run", ok_run):
            return {name: (ok, detail) for name, ok, detail in vl.check(self.clone, None)}


class Manifest(Base):
    def test_a_clean_checkout_passes(self):
        self.write()
        failed = [n for n, (ok, _) in self.results().items() if not ok]
        self.assertEqual(failed, [])

    def test_a_blank_hash_is_an_error_even_if_the_file_changed(self):
        self.write(blank="b.md")
        (self.clone / "b.md").write_bytes(b"# changed\n")
        r = self.results()
        self.assertFalse(r["the launch manifest parses strictly"][0])
        self.assertFalse(r["every launch hash matches"][0])

    def test_repeated_rows_and_unknown_dispositions_are_errors(self):
        self.write(rows=[f"| `a.md` | unchanged |  |  | `{h(self.files['a.md'])}` |",
                         f"| `b.md` | mystery |  |  | `{h(self.files['b.md'])}` |"])
        detail = self.results()["the launch manifest parses strictly"]
        self.assertFalse(detail[0])
        self.assertIn("repeated row", detail[1])

    def test_unrecorded_archive_only_checks_fail(self):
        self.write(checks=False)
        self.assertFalse(self.results()["archive-only checks recorded as run"][0])


class Links(Base):
    def test_a_link_outside_the_tree_fails_even_if_the_target_exists(self):
        outside = self.clone.parent / "outside.md"
        outside.write_text("x\n", encoding="utf-8")
        self.files["a.md"] = b"# A\n\nSee [out](../outside.md).\n"
        self.write()
        ok, detail = self.results()["relative links resolve"]
        self.assertFalse(ok)
        self.assertIn("../outside.md", detail)


class PrivateScan(Base):  # GPT-6 LX1, topic launch-export, round 3: layered escapes in raw text
    KEY, TERM = "k3y-VALUE-8", "zebra-topic"

    def private(self):
        repo = Path(self.tmp.name) / "repo"
        repo.mkdir()
        (repo / "a.md").write_text("# A\n", encoding="utf-8")
        for args in (("init", "-q"), ("config", "user.email", "t@example.invalid"), ("config", "user.name", "t"),
                     ("add", "-A"), ("commit", "-q", "-m", "x")):
            subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)
        root = Path(self.tmp.name)
        (root / "keys.env").write_text(f"SOME_API_KEY={self.KEY}\n", encoding="utf-8")
        (root / "summaries.json").write_text("{}", encoding="utf-8")
        (root / "launch.json").write_text(json.dumps({"version": "t", "source_commit": "HEAD", "identifiers": [],
                                                      "grok_summaries": str(root / "summaries.json")}), encoding="utf-8")
        (root / "export.json").write_text(json.dumps({"keys_file": str(root / "keys.env"), "terms": [],
                                                      "withhold_terms": [{"text": self.TERM, "category": "personal"}]}),
                                          encoding="utf-8")
        return {"repo": str(repo), "launch": str(root / "launch.json"), "export": str(root / "export.json")}

    def test_a_key_or_withheld_term_encoded_twice_in_raw_text_is_found(self):
        private = self.private()
        twice = "".join(f"%25{ord(c):02X}" for c in self.KEY + " " + self.TERM)  # percent-encoded twice
        # a YAML comment is in the raw text only: not a parsed value, not the body
        self.files["notes/c.md"] = f"---\ntitle: t\n# {twice}\n---\n\n# C\n".encode()
        self.write()
        with mock.patch.object(vl, "run", ok_run):
            r = {name: (ok, detail) for name, ok, detail in vl.check(self.clone, private)}
        self.assertFalse(r["private scan: key values"][0])
        self.assertFalse(r["private scan: configured terms"][0])
        self.assertTrue(r["private scan: identifiers, literals or Grok spans"][0])


class Archive(Base):
    def test_archive_files_without_their_manifest_fail(self):  # GPT-6 LX2, round 2
        self.files.update({"sessions/a/t.txt": b"evidence\n", "sessions/a/t.txt.meta.md": b"sidecar\n"})
        self.write()
        ok, detail = self.results()["the archive matches its own manifest"]
        self.assertFalse(ok)
        self.assertIn("no manifest", detail)

    def test_an_archive_file_changed_after_export_fails(self):
        data = b"evidence\n"
        self.files.update({"sessions/a/t.txt": data, "sessions/a/t.txt.meta.md": b"sidecar\n"})
        self.files["sessions/manifest.md"] = (
            f"| `sessions/a/t.txt` | text | published | `{'0' * 64}` | `{h(data)}` | none | none |\n").encode()
        self.write()
        self.assertTrue(self.results()["the archive matches its own manifest"][0])
        self.files["sessions/a/t.txt"] = b"altered\n"
        self.write()  # the launch manifest is rewritten to match; only the archive manifest can catch it
        r = self.results()
        self.assertTrue(r["every launch hash matches"][0])
        self.assertFalse(r["the archive matches its own manifest"][0])


if __name__ == "__main__":
    unittest.main()
